apiVersion: v1
kind: PersistentVolume
metadata:
  name: {{ include "disks.fullname" . }}-seq-pv
spec:
  capacity:
    storage: {{ .Values.seq.capacity.storage }}
  storageClassName: managed-premium
  volumeMode: Filesystem
  accessModes:
    - ReadWriteOnce
  azureDisk:
    kind: Managed
    diskName: {{ .Values.seq.azureDisk.diskName }}
    diskURI: {{ .Values.seq.azureDisk.diskURI }}
