apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ include "disks.fullname" . }}-seq-pvc
spec:
  accessModes:
  - ReadWriteOnce
  storageClassName: managed-premium
  resources:
    requests:
      storage: {{ .Values.seq.capacity.storage }}
